language: python
python:
  - "3.4"
before_install:
  - sudo add-apt-repository -y ppa:team-electronics/ppa
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq iverilog-daily
script:
  - cd test
  - make
  
