sudo: required
dist: trusty
group: deprecated-2017Q4
language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - sudo add-apt-repository -y ppa:team-electronics/ppa
  - sudo apt-get update -qq
  - wget ftp://icarus.com/pub/eda/verilog/v10/verilog-10.2.tar.gz
  - tar xvf verilog-10.2.tar.gz
  - cd verilog-10.2
  - ./configure
  - make
  - sudo make install
  - cd ..
install:
  - pwd
  - git clone https://github.com/potentialventures/cocotb
script:
  - ls
  - cd verilog_uart
  - ls
  - cd test
  - ls
  - make
  
