language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - sudo add-apt-repository -y ppa:team-electronics/ppa
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq iverilog-daily
  - git clone https://github.com/potentialventures/cocotb
script:
  - cd test
  - make
  
