sudo: required
services:
  - docker
language: python
python:
  - "3.4"
before_install:
  - sudo docker build -t hdl -f docker/Dockerfile .
install:
script:
  - sudo docker run --rm -v verilog_uart:/verilog_uart hdl bash -c "cd verilog_uart/test; make"
  
