sudo: required
dist: xenial
group: deprecated-2017Q4
language: python
python:
  - "3.6"
before_install:
  - sudo add-apt-repository -y ppa:team-electronics/ppa
  - sudo apt-get update -qq
  - wget ftp://icarus.com/pub/eda/verilog/v10/verilog-10.2.tar.gz
  - tar xvf verilog-10.2.tar.gz
  - cd verilog-10.2
  - ./configure
  - make
  - sudo make install
  - cd ..
install:
  - cd ..
  - git clone https://github.com/forensicgarlic/cocotb
  - cd cocotb
  - git checkout dls_own_hands
  - cd ..
script:
  - cd verilog_uart
  - make COCOTB_REDUCED_LOG_FMT=true COCOTB_ANSI_OUTPUT=0
  - (exit $(find -name results.xml | xargs grep "failure message" | wc -l))

